In [2]:
import pandas as pd
import numpy as np
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler as ss

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_csv('heart_disease.csv')

print("Dataset Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

Dataset Shape: (10000, 21)

First 5 rows:

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   str
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   str
 5   Smoking               9975 non-null   str
 6   Family Heart Disease  9979 non-null   str
 7   Diabetes              9970 non-null   str
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   str
 10  Low HDL Cholesterol   9975 non-null   str
 11  High LDL Cholesterol  9974 non-null   str
 12  Alcohol Consumption   7414 non-null   str
 13  Stress Level          9978 non-null   str
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   str
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  str
dtypes: float64(9), str(12)
memory usage: 1.6 MB

In [5]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(10000, 21)
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   str
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   str
 5   Smoking               9975 non-null   str
 6   Family Heart Disease  9979 non-null   str
 7   Diabetes              9970 non-null   str
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   str
 10  Low HDL Cholesterol   9975 non-null   str
 11  High LDL Cholesterol  9974 non-null   str
 12  Alcohol Consumption   7414 non-null   str
 13  Stress Level          9978 non-null   str
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   str
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  str
dtypes: float64(9), str(12)
memory usage: 1.6 MB
None
Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [6]:
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [7]:
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2900\2373410678.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2900\2373410678.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].mode()[0], inplace=True)

In [8]:
print(df.dtypes)

Age                     float64
Gender                      str
Blood Pressure          float64
Cholesterol Level       float64
Exercise Habits             str
Smoking                     str
Family Heart Disease        str
Diabetes                    str
BMI                     float64
High Blood Pressure         str
Low HDL Cholesterol         str
High LDL Cholesterol        str
Alcohol Consumption         str
Stress Level                str
Sleep Hours             float64
Sugar Consumption           str
Triglyceride Level      float64
Fasting Blood Sugar     float64
CRP Level               float64
Homocysteine Level      float64
Heart Disease Status        str
dtype: object

In [9]:
df.replace(['?', 'NA', 'None', ''], np.nan, inplace=True)
print(df.dtypes)

Age                     float64
Gender                      str
Blood Pressure          float64
Cholesterol Level       float64
Exercise Habits             str
Smoking                     str
Family Heart Disease        str
Diabetes                    str
BMI                     float64
High Blood Pressure         str
Low HDL Cholesterol         str
High LDL Cholesterol        str
Alcohol Consumption         str
Stress Level                str
Sleep Hours             float64
Sugar Consumption           str
Triglyceride Level      float64
Fasting Blood Sugar     float64
CRP Level               float64
Homocysteine Level      float64
Heart Disease Status        str
dtype: object

In [10]:
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    if df[col].isnull().sum() > 0:
        if not df[col].mode().empty:
            df[col] = df[col].fillna(df[col].mode()[0])
        else:
            df[col] = df[col].fillna("Unknown")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2900\1691255245.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns

In [11]:
df.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [12]:
X = df.drop("Heart Disease Status", axis=1)
y = df["Heart Disease Status"]

In [13]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, ..., 1, 1, 1], shape=(10000,))

In [14]:
num_features = X.select_dtypes(include=np.number).columns
cat_features = X.select_dtypes(include='object').columns

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2900\1644640969.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X.select_dtypes(include='object').columns

In [15]:
print("Heart Disease Status — Unique values:")
print(df['Heart Disease Status'].value_counts())

print("\nExercise Habits — Unique values:")
print(df['Exercise Habits'].value_counts())

Heart Disease Status — Unique values:
Heart Disease Status
No     8000
Yes    2000
Name: count, dtype: int64

Exercise Habits — Unique values:
Exercise Habits
High      3397
Medium    3332
Low       3271
Name: count, dtype: int64

In [16]:
# --- Label Encoding ---
le = LabelEncoder()

# Fit and transform the column
df['Heart Disease Status_Encoded'] = le.fit_transform(df['Heart Disease Status'].astype(str))

# Display mapping
print("Label Encoding Mapping:")
mapping = dict(zip(le.classes_, le.transform(le.classes_)))
for original, encoded in mapping.items():
    print(f"  '{original}' → {encoded}")

print("\nBefore and After Label Encoding:")
df[['Heart Disease Status', 'Heart Disease Status_Encoded']].head(10)

Label Encoding Mapping:
  'No' → 0
  'Yes' → 1

Before and After Label Encoding:

  Heart Disease Status  Heart Disease Status_Encoded
0                   No                             0
1                   No                             0
2                   No                             0
3                   No                             0
4                   No                             0
5                   No                             0
6                   No                             0
7                   No                             0
8                   No                             0
9                   No                             0

In [17]:
# --- One-Hot Encoding ---
ohe_df = pd.get_dummies(
    df['Exercise Habits'],
    prefix='Exercise Habits',
    dummy_na=False      # Set True if you want a column for NaN values
)

# Concatenate OHE columns back to the dataframe
df = pd.concat([df, ohe_df], axis=1)

print("One-Hot Encoded columns created:")
print(ohe_df.columns.tolist())

print("\nBefore and After One-Hot Encoding:")
ohe_cols = ['Exercise Habits'] + ohe_df.columns.tolist()
df[ohe_cols].head(10)

One-Hot Encoded columns created:
['Exercise Habits_High', 'Exercise Habits_Low', 'Exercise Habits_Medium']

Before and After One-Hot Encoding:

,Exercise Habits,Exercise Habits_High,Exercise Habits_Low,Exercise Habits_Medium
0,High,True,False,False
1,High,True,False,False
2,Low,False,True,False
3,High,True,False,False
4,Low,False,True,False
5,Low,False,True,False
6,High,True,False,False
7,Low,False,True,False
8,Low,False,True,False
9,Low,False,True,False

In [18]:
encoded_cols = [
    'Heart Disease Status', 'Heart Disease Status_Encoded',
    'Exercise Habits',
    'Exercise Habits_High', 'Exercise Habits_Low', 'Exercise Habits_Medium'
]

print("Final Encoded DataFrame (selected columns):")
df[encoded_cols].head(10)

Final Encoded DataFrame (selected columns):

,Heart Disease Status,Heart Disease Status_Encoded,Exercise Habits,Exercise Habits_High,Exercise Habits_Low,Exercise Habits_Medium
0,No,0,High,True,False,False
1,No,0,High,True,False,False
2,No,0,Low,False,True,False
3,No,0,High,True,False,False
4,No,0,Low,False,True,False
5,No,0,Low,False,True,False
6,No,0,High,True,False,False
7,No,0,Low,False,True,False
8,No,0,Low,False,True,False
9,No,0,Low,False,True,False

In [19]:
print("Data types of encoded columns:")
print(df[encoded_cols].dtypes)

Data types of encoded columns:
Heart Disease Status              str
Heart Disease Status_Encoded    int64
Exercise Habits                   str
Exercise Habits_High             bool
Exercise Habits_Low              bool
Exercise Habits_Medium           bool
dtype: object

In [20]:
# Numerical → Scaling
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder


num_transformer = ss()

# Categorical → One-Hot Encoding
cat_transformer = OneHotEncoder(drop='first', handle_unknown='ignore')

# Combine
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, num_features),
        ('cat', cat_transformer, cat_features)
    ]
)
print("Preprocessor created successfully!")

Preprocessor created successfully!

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [22]:
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

print("Encoded Train Shape:", X_train_encoded.shape)
print("Encoded Test Shape:", X_test_encoded.shape)

Encoded Train Shape: (8000, 24)
Encoded Test Shape: (2000, 24)

In [23]:
df.head(10)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Heart Disease Status_Encoded,Exercise Habits_High,Exercise Habits_Low,Exercise Habits_Medium
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,Medium,342.0,120.0,12.969246,12.387250,No,0,True,False,False
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,Medium,133.0,157.0,9.355389,19.298875,No,0,True,False,False
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Low,393.0,92.0,12.709873,11.230926,No,0,False,True,False
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,High,293.0,94.0,12.509046,5.961958,No,0,True,False,False
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,High,263.0,154.0,10.381259,8.153887,No,0,False,True,False
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,Low,126.0,91.0,4.297575,10.815983,No,0,False,True,False
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,Medium,107.0,85.0,11.582983,19.659461,No,0,True,False,False
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,...,High,228.0,111.0,4.929381,17.146599,No,0,False,True,False
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,...,High,317.0,103.0,5.119015,6.051129,No,0,False,True,False
9,75.0,Male,144.0,252.0,Low,Yes,Yes,No,30.142149,No,...,High,199.0,96.0,10.005698,7.604357,No,0,False,True,False