In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler as ss

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv('train.csv')

print("Dataset Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

Dataset Shape: (8068, 9)

First 5 rows:

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   str
 2   Ever_Married     7928 non-null   str
 3   Age              8068 non-null   int64
 4   Graduated        7990 non-null   str
 5   Profession       7944 non-null   str
 6   Work_Experience  7239 non-null   float64
 7   Spending_Score   8068 non-null   str
 8   Family_Size      7733 non-null   float64
dtypes: float64(2), int64(2), str(5)
memory usage: 567.4 KB

In [10]:
print(df.shape)
print(df.info())
print(df.head())
print(df.isnull().sum())

(8068, 9)
<class 'pandas.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   int64
 2   Ever_Married     8068 non-null   int64
 3   Age              8068 non-null   int64
 4   Graduated        8068 non-null   int64
 5   Profession       8068 non-null   int64
 6   Work_Experience  8068 non-null   float64
 7   Spending_Score   8068 non-null   int64
 8   Family_Size      8068 non-null   float64
dtypes: float64(2), int64(7)
memory usage: 567.4 KB
None
       ID  Gender  Ever_Married  Age  Graduated  Profession  Work_Experience  \
0  462809       1             0   22          0           5              1.0
1  462643       0             1   38          1           2              1.0
2  466315       0             1   67          1           2              1.0
3  461735       1             1   67          1           7              0.0
4  462669       0             1   40          1           3              1.0

   Spending_Score  Family_Size
0               2          4.0
1               0          3.0
2               2          1.0
3               1          2.0
4               1          6.0
ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
dtype: int64

In [5]:
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())
cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_7144\2290395953.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

In [6]:
isnull = df.isnull().sum()
print(isnull)

ID                 0
Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
dtype: int64

In [7]:
le=LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [8]:
df.head(10)

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size
0,462809,1,0,22,0,5,1.0,2,4.0
1,462643,0,1,38,1,2,1.0,0,3.0
2,466315,0,1,67,1,2,1.0,2,1.0
3,461735,1,1,67,1,7,0.0,1,2.0
4,462669,0,1,40,1,3,1.0,1,6.0
5,461319,1,1,56,0,0,0.0,0,2.0
6,460156,1,0,32,1,5,1.0,2,3.0
7,464347,0,0,33,1,5,1.0,2,3.0
8,465015,0,1,61,1,2,0.0,2,3.0
9,465176,0,1,55,1,0,1.0,0,4.0

In [9]:
print(df.dtypes)

ID                   int64
Gender               int64
Ever_Married         int64
Age                  int64
Graduated            int64
Profession           int64
Work_Experience    float64
Spending_Score       int64
Family_Size        float64
dtype: object